<a href="https://colab.research.google.com/github/meganhsu/ML100-Days/blob/master/Day_063_HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 作業
* 在精簡深度學習的方式上 : 卷積類神經 (CNN) 採用像素遠近，而遞歸類神經 (RNN) 採用著則是時間遠近
* 那麼，既然有著類似的設計精神，兩者是否有可能互換應用呢?

In [0]:
import numpy as np
import random
#Input array

X = np.array([[1, 0, 1, 0], [1 ,0 ,1 ,1 ],[ 0 , 1 , 0 , 1 ]])

#Output
y = np.array([[1], [1], [0]])

In [0]:
#Sigmoid Function
def sigmoid(x): 
    return  1/(1+np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x): 
    return x*(1-x)

In [0]:
#Variable initialization
epoch = 5000 #Setting training iterations
lr = 0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set 
print("inputlayer_neurons=%s"%(inputlayer_neurons))
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

inputlayer_neurons=4


In [0]:
#weight and bias initialization
random.seed(1)
wh = np.random.uniform( size = ( inputlayer_neurons , hiddenlayer_neurons ) ) 
bh = np.random.uniform( size = ( 1 , hiddenlayer_neurons ) ) 
wout = np.random.uniform( size = ( hiddenlayer_neurons , output_neurons ) ) 
bout = np.random.uniform( size = ( 1 , output_neurons ) )

In [0]:
for i in  range ( epoch ) :
    #Forward Propogation
    hidden_layer_input1 = np.dot(X, wh) 
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations =  sigmoid( hidden_layer_input ) 
print(X)
print(hiddenlayer_activations)

[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
[[0.89480338 0.89199728 0.82985343]
 [0.90035448 0.95145186 0.86513031]
 [0.78029912 0.8624692  0.79705932]]


In [0]:
for i in  range ( epoch ) :
    '''
    寫出output Layer
    '''
    hidden_layer_input1 = np.dot(hiddenlayer_activations, wout) 
    hidden_layer_input = hidden_layer_input1 + bout
    output = sigmoid( hidden_layer_input ) 
    
print ( "output of Forward Propogation:\n{}" .format(output)) 
print ( "wout,bout of Backpropagation:\n{},\n{}" .format(wout, bout ))

output of Forward Propogation:
[[0.83507326]
 [0.84321734]
 [0.82405124]]
wout,bout of Backpropagation:
[[0.36217728]
 [0.6884675 ]
 [0.49332898]],
[[0.27443878]]
